version: '3.1'

services:
  postgres:
    restart: always
    container_name: DRFTask_postgres
    expose:
      - 5432
    build:
      context: .
      dockerfile: dockerfiles/docker_postgres.conf
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  django:
    restart: always
    container_name: DRFTask_django
    volumes:
      - ./code:/code
      - ./sock:/sock
    build:
      context: .
      dockerfile: dockerfiles/docker_django.conf
    depends_on:
      - postgres
    #command: uwsgi --ini /config/uwsgi/uwsgi.ini
    command: bash -c "python /code/DRFTask/manage.py makemigrations && python /code/DRFTask/manage.py migrate && python /code/DRFTask/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

  nginx:
    restart: always
    container_name: DRFTask_nginx
    volumes:
      - ./code:/code
      - ./sock:/sock
    build:
      context: .
      dockerfile: dockerfiles/docker_nginx.conf
    depends_on:
      - django
    ports:
      - "8080:8080"